[tool.ruff]
line-length = 88
target-version = "py312"
exclude = [
    "migrations",
    "venv",
    "env",
    "build",
    "dist",
    ".venv",
    ".env",
    "__pycache__",
    "reset_votes.py",
]

[tool.ruff.lint]
select = [
    "E", "F", "I", "B", "UP", "C90", "N", "A", "C4", "SIM", "T20", "RET", "ARG", "DTZ", "PL", "RUF"
]

ignore = [
    "E501", # Handled by Black
    "B008", # Do not perform function calls in argument defaults (sometimes needed)
    "ERA",  # Allow commented-out code and lots of comments
    "UP017", # Allow f-string with single expressions (for timezone.utc errors)
    "PLR2004", # Allow magic value comparisons where acceptable
    "T201", # For print statements
    "C901", # For function too complex
    "PLR0915", # Too many statements
    "PLR0911", # Too many return statements
    "PLR0912", # Too many branches
    "PLR0913", # Too many arguments
]

[tool.ruff.lint.isort]
known-first-party = ["app", "models"]
force-sort-within-sections = true
section-order = ["standard-library", "first-party", "third-party"]
default-section = "first-party"
lines-after-imports = 2

[tool.ruff.format]
docstring-code-format = true

[tool.black]
line-length = 88
target-version = ["py312"]
skip-string-normalization = false
